baseURL = "/"
languageCode = "en-us"
title = "UET Learning Course"
pagination.pagerSize = 20

taxonomies = {}

[markup]
  [markup.highlight]
    noClasses = false
    style = "github"
    lineNos = false
    lineNumbersInTable = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      wrapCodeBlock = false
